version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ://amazonaws.com
  build:
    commands:
      - docker build -t website:latest .
      - docker tag website:latest ://amazonaws.com/website:latest
  post_build:
    commands:
      - echo "Checking local images..."
      - docker images
      - echo "Pushing..."
      - docker push ://amazonaws.com/website:latest

